## *Description*: 
##the makeCacheMatrix function produces a special matrix that can cache its inverse. 
##the cacheSolve function returns the inverse of the matrix produced by makeCacheMatrix function
##cacheSolve checks if the inverse of the matrix is already calculated and the matrix has not changed
##If the inverse is already calculated and the matrix is unchanged, the inverse is retrieved from the cache and returned.
##otherwise it finds the inverse, caches it and returns it
##The inverse of a square matrix is found by using the solve function in R

## *makeCacheMarix* function creates a special matrix which is a list that does the following:
## 1. Sets the value of the matrix
## 2. Gets the value of the matrix
## 3. Sets the value of the inverse 
## 4. Gets the value of the inverse

makeCacheMatrix <- function(x = matrix()) {
                 i <- NULL
                 set <- function(y){
                   x <<- y
                   i <<- NULL
                 }
                 get <- function () x
                 setinverse <- function(inverse) i <<- inverse
                 getinverse <- function() i
                 list(set=set, get=get, setinverse=setinverse, getinverse=getinverse)

                 }


## The function cacheSolve produces the inverse of the matrix generated by makeCacheMatrix funtion
##The function will first look for the inverse in the cache, it returns the inverse if it was calculated and the matrix is the same
##If the inverse is not found in the cache, the function computes the inverse, caches and returns it.

cacheSolve <- function(x, ...) {
        i <- x$getinverse()
        if(!is.null(i)){
          message("getting cached data")
          return(i)
        }
        data <- x$get()
        i <- solve(data,...)
        x$setinverse(i)
        i
        
}
